name = "SlurmHyperopt"
uuid = "cc751f0e-ca47-473a-90b9-8165154f6533"
authors = ["Maximilian Gelbrecht <maximiliaan.gelbrecht@posteo.de> and contributors"]
version = "0.1.0"

[deps]
Hyperopt = "93e5fe13-2215-51db-baaf-2e9a34fb2712"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
